### ISSUE TITLE
How about making `Scalar` as the basic generic argument?

### ISSUE THREAD

**Issue by sundy-li** [skyzh/type-exercise-in-rust#2]
Hello, good to see such a fantastic `type-exercise` in rust.

I thought the `Array` and `Scalar` are mutual injective, so how about making the `Scalar` as the basic generic arg?

```
let expr = BinaryExpression::<StringArray, StringArray, BoolArray, _>::new(str_contains);
```

=> 

```
let expr = BinaryExpression::<String, String, bool , _>::new(str_contains);
```

**Comment by skyzh** [comment]
It is possible with some extra trait bounds, but might be hard to implement in this system.

```rust
pub trait Scalar:
    std::fmt::Debug + Clone + Send + Sync + 'static + TryFrom<ScalarImpl> + Into<ScalarImpl>
{
    /// The corresponding [`Array`] type.
    type ArrayType: Array<OwnedItem = Self>;

    /// The corresponding [`ScalarRef`] type.
    type RefType<'a>: ScalarRef<'a, ScalarType = Self, ArrayType = Self::ArrayType>
    where
        Self: 'a;

    /// Get a reference of the current value.
    fn as_scalar_ref(&self) -> Self::RefType<'_>;
}
```

We did not add constraints for `Scalar::ArrayType::RefType = Self::RefType` in `Scalar::ArrayType`. Therefore, if we use `Scalar` in generics, and when we want to `array.push(ScalarRef)`, we will need to add some further bounds to make the whole thing compile.

The current type system design is aimed to use `Array` in all occurrence of generic parameters. As you can see in the map of types:


![](https://github.com/skyzh/type-exercise-in-rust/raw/master/map-of-types.png)



`Array` is at the center of all traits -- we can always access other traits within one hop from `Array`.

Anyway, I would be happy to accept a PR if someone succeeded to use `Scalar` in `BinaryExpression`. Thanks for your comments!

**Comment by sundy-li** [comment]
Great to hear your explanation, thanks Mr Chi.

To be honest, I was redesigning Type System in `databend` over the past two weeks.  
Yet I was not very familiar with Rust's `GAT` before, so this exercise is really helpful and inspires me a lot.


I just made a simple hack on `databend` and it shows using `Scalar` in `BinaryExpression` can work.

https://github.com/sundy-li/databend/blob/type-exercise/common/functions/src/scalars/expressions/binary.rs#L74-L106


Yet in `databend` , not all arrays are scalar arrays, we have `ConstColumn` & `StructColumn` & `ArrayColumn`. So we just make `primitive types` & `bool` & `String` as Scalar Types for now.


I have another question `ArrayImpl` seems to be over design for me, we can use downcast to get rid of enum match. 
Is that for performance that enum match has lower cast than downcast ?

**Comment by skyzh** [comment]
> https://github.com/sundy-li/databend/blob/type-exercise/common/functions/src/scalars/expressions/binary.rs#L74-L106

Looks good! I'll see if it is possible to adapt `Scalar`-central generic design into this repo.

> I have another question ArrayImpl seems to be over design for me, we can use downcast to get rid of enum match.
Is that for performance that enum match has lower cast than downcast ?

The `Array` trait has associated types, while those types are used in trait functions, so it isn't possible to directly make it into a `Box<dyn Array>`. Therefore, we must find a way to dispatch those methods.

It's either okay to use `enum ArrayImpl` or `pub struct ArrayImpl(Box<dyn Any>)`, and I don't think there are much difference between their performance. In this example, we used `ArrayImpl`, which is a enum.

If we want to use `Box<dyn Any>` for `ArrayImpl`, we still need to implement a dispatch function.

e.g., we may need to write something like,

```rust
impl ArrayImpl {
  pub fn get(&self, idx: usize) -> ScalarRefImpl<'_> {
    match self.0.type_id() {
      TypeId::of::<StringArray>() => downcast_ref::<StringArray>(self.0).get(idx).map(ScalarRefImpl::String)
    }
  }
}
```

The above example might not compile, it's just an idea on how to implement the same functionality with a boxed Array.

Anyway, if you don't need to operate on the `Array` collection level (in this case, always downcast and get data), you don't need to implement dispatch functions either an enum `ArrayImpl`, nor a boxed dyn `ArrayImpl`.

**Comment by skyzh** [comment]
Hi @sundy-li, I've updated the tutorial with "day 6 - the hard way" and "day 7 - the hard way". In the new chapters, we use `Scalar` to unify those generic functions. At the same time, we don't need to create a struct for every function. We can directly vectorize a plain function.

**Comment by skyzh** [comment]
Examples:

```rust
let expr = BinaryExpression::<String, String, bool, _>::new(str_contains);
```

instead of

```rust
let expr = BinaryExpression::<StringArray, StringArray, BoolArray, _>::new(ExprStrContains);
```

**Comment by sundy-li** [comment]
Great! Let's close the issue.

**Comment by skyzh** [comment]
> I have another question ArrayImpl seems to be over design for me, we can use downcast to get rid of enum match.
Is that for performance that enum match has lower cast than downcast ?

I've added an example for BoxedArray in day 9. FYI, https://github.com/skyzh/type-exercise-in-rust/commit/403f8e8c10209295f3fa402ff40dd7e7a4cb6858
